baseURL = "http://macprecision.net"
languageCode = "de-de"
title = "MAC Precision"
theme = "navigator-hugo"
summaryLength = 10


# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "de"

# Site Params
[params]
logo = "images/logo.png"
phone = "images/phone.png"
    
# Gestion des langues :.de / EN / NL / DE
[[Params.listeLangues]]
code = "de"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"

# Gestion des langues :.de / EN / NL / DE
[Languages]
############ 1 - Site in GERMAN
[Languages.de]
weight = 1
languageCode = "de-de"
title = "MAC Precision"
dateFormat = "2. Januar 2006"

home = "Home"
logo = "images/logo.png"
phone = "images/phone.png"
menufixed = true

footerDescription = "Seit 2012 erkennt, prüft und stellt Mac Precision seinen Kunden Qualitätslieferanten vor."
footerServiceTitle = "Leistungen"
footerQuicklinkTitle = "Nützliche Links"
footerAboutTitle = "Über uns"
footerSubscribeTitle = "Abonniere uns"

# Hero Area Section
[Languages.de.params.hero]
enable  = true
heading = "Die richtige Adresse für mechanische Bauteile aller Art"
description = "Unsere Partnerunternehmen setzen auf neuste Technologien und höchste Standards"
button  = false
btnText = "mehr erfahren"
btnURL  = "/de"
carouselThumb1 = "images/slider/car_tedisa.jpg"
carouselThumb2 = "images/slider/car_tdg3.jpg"
carouselThumb3 = "images/slider/car_grindel2.jpg"
carouselThumb4 = "images/slider/car_oz.jpg"
carouselThumb5 = "images/slider/car_eisenor.jpg"
carouselThumb6 = "images/slider/car_grindel.jpg"
carouselThumb7 = "images/slider/car_shuton.jpg"
carouselThumb8 = "images/slider/car_spiroide.jpg"
carouselTitle1 = "images/slider/title_tedisa.png"
carouselTitle2 = "images/slider/title_tdg.png"
carouselTitle3 = "images/slider/title_grindel.png"
carouselTitle4 = "images/slider/title_oz.png"
carouselTitle5 = "images/slider/title_eisenor.png"
carouselTitle6 = "images/slider/title_grindel.png"
carouselTitle7 = "images/slider/title_shuton.png"
carouselTitle8 = "images/slider/title_spiroide.png"

# About 2 Section
[Languages.de.params.aboutSm]
enable  = true
title   = "Mac Precision entdeckt und überprüft bereits seit 2012 Lieferanten mit hohen Qualitätsstandards und stellt sie seinen Kunden vor."
description = "Die Zahl unserer zufriedenen Kunden, die unseren zuverlässigen Lieferanten mit ihren Produkten zu marktfähigen Preisen vertrauen, wächst kontinuierlich.  Die Lieferanten sind kleine bis mittelgroße Traditions- und Familienunternehmen."

# Blog Section On Homepage
[Languages.de.params.blog]
enable  = false
topTitle= "Unsere Geschichte"
title   = "News"
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.de.params.contact]
enable  = true
topTitle= "IHR KONTAKT"
title   = "SCHREIBEN SIE UNS."
subtitle= "Wir helfen Ihnen gerne bei allen möglichen Fragen."
address = "Postfach 240229<br> 68172 Mannheim"
phone   = "+49 (0) 621 481 9878"
phone2  = "+49 (0) 176 966 183 30"
email   = "jadavidson@macprecision.de"
email2  = "tbentgens@macprecision.de"

facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.de.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Lasst uns zusammen Ideen verwirklichen"
subtitle= "Für uns dreht sich alles um guten Service und<br>Zusammenarbeit auf Augenhöhe."
btnText = "Zum Kontakt"

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "Example site multi-language"
dateFormat = "January 2, 2006"

home = "Home"
logo = "images/logo.png"
phone = "images/phone.png"
menufixed = true

footerDescription = "We have been discovering, auditing, and introducing quality providers to our customers since 2012."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Die richtige Adresse für mechanische Bauteile aller Art"
description = "Unsere Partnerunternehmen setzen auf neuste Technologien und höchste Standards"
button  = false
btnText = "mehr erfahren"
btnURL  = "/en"
carouselThumb1 = "images/slider/car_tedisa.jpg"
carouselThumb2 = "images/slider/car_tdg3.jpg"
carouselThumb3 = "images/slider/car_grindel2.jpg"
carouselThumb4 = "images/slider/car_oz.jpg"
carouselThumb5 = "images/slider/car_eisenor.jpg"
carouselThumb6 = "images/slider/car_grindel.jpg"
carouselThumb7 = "images/slider/car_shuton.jpg"
carouselThumb8 = "images/slider/car_spiroide.jpg"
carouselTitle1 = "images/slider/title_tedisa.png"
carouselTitle2 = "images/slider/title_tdg.png"
carouselTitle3 = "images/slider/title_grindel.png"
carouselTitle4 = "images/slider/title_oz.png"
carouselTitle5 = "images/slider/title_eisenor.png"
carouselTitle6 = "images/slider/title_grindel.png"
carouselTitle7 = "images/slider/title_shuton.png"
carouselTitle8 = "images/slider/title_spiroide.png"


# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "MAC Precision has been discovering, auditing, and introducing quality providers to its’ customers since 2012."
description = "Today we have an ever-growing group of satisfied customers that rely on MAC Precisions’ suppliers to deliver quality components on a timely basis with market prices. These suppliers are for the most part small to medium sized traditional or family companies."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "OUR UNTOLD STORY"
title   = "News"
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= "We'll answer all the questions you have regarding MAC Precision."
address = "Postfach 240229<br> 68172 Mannheim"
phone   = "+49 (0) 621 481 9878"
phone2  = "+49 (0) 176 966 183 30"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "49.450759"
mapLongitude= "8.472489"
mapMarker   = "images/marker.png"
email   = "jadavidson@macprecision.de"
email2  = "tbentgens@macprecision.de"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Our ambition is to deliver perfect components and services<br> We care about our customer relations."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "service"
url     = "service"
identifier = "service"
weight  = 1
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
identifier = "portfolio"
weight  = 2
[[menu.nav]]
name    = "blog"
url     = "blog"
identifier = "blog"
weight  = 3
[[menu.nav]]
name    = "contact"
url     = "contact"
identifier = "contact"
weight  = 4



# Footer Service Menu
[[menu.service]]
name    = "service"
url     = "service"
weight  = 6
[[menu.service]]
name    = "partner"
url     = "portfolio"
weight  = 7
[[menu.service]]
name    = "contact"
url     = "contact"
weight  = 8

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "contact"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "service"
weight  = 2
[[menu.quicklink]]
name    = "news"
url     = "blog"
weight  = 3
